apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Release.Namespace }}-demo-idp-database
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gcpProject.id }}
    cnrm.cloud.google.com/deletion-policy: "abandon"
spec:
  charset: utf8
  instanceRef:
    external: {{ .Values.infrastructure.postgresInstanceName }}
