apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-idp-ingress
spec:
  ingressClassName: ip
  rules:
    - host: demo-idp.{{ .Values.ingress.clusterIpDomain }}
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: demo-idp-service
                  port:
                    name: service-port
---
apiVersion: v1
kind: Service
metadata:
  name: demo-idp-service
spec:
  type: ClusterIP
  selector:
    app: demo-idp
  ports:
    - name: service-port
      port: 7999
      targetPort: kc-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-idp

spec:
  selector:
    matchLabels:
      app: demo-idp

  replicas: 1
  template:
    metadata:
      labels:
        app: demo-idp
    spec:
      serviceAccount: {{ .Values.gke.serviceAccount }}
      containers:
        - name: demo-idp
          image: quay.io/keycloak/keycloak:16.1.0
          ports:
            - name: kc-container
              containerPort: 8080
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: {{ .Values.cloudSql.host }}:5432
            - name: DB_DATABASE
              value: {{ .Release.Namespace }}-demo-idp-database
            - name: DB_USER
              value: {{ .Release.Namespace }}-demo-idp-sqluser
            - name: DB_PASSWORD
              value: {{ .Values.sqluser.password }}
